services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://archive.org/download/en_windows_server_2022x64_dvd_/en_windows_server_2022x64_dvd_.iso"
      BOOT_MODE: "legacy
      DISK_TYPE: "blk"
      REGION: en-GB
      KEYBOARD: en-GB
      DISK_SIZE: 62GB
      RAM_SIZE: 4G
      CPU_CORES: "4"
      USERNAME: Docker
      PASSWORD: Gates
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
