services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      LANGUAGE: English
      REGION: en-GB
      KEYBOARD: en-GB
      DISK_SIZE: 62GB
      RAM_SIZE: 4G
      CPU_CORES: "4"
      USERNAME: Ronak
      PASSWORD: R11
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./tmp:/storage
    restart: always
    stop_grace_period: 2m
