services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/6.2.8250.0.winmain-win-8beta.-120217-1520-amd-64fre-client-prerelease-retail-en-_202406/6.2.8250.0.winmain_win8beta.120217-1520_amd64fre_client-prerelease_retail_en-us-HB1_CCPA_X64FRE_EN-US_DV5.iso"
      LANGUAGE: English
      REGION: en-GB
      KEYBOARD: en-GB
      DISK_SIZE: 62GB
      RAM_SIZE: 4G
      CPU_CORES: "4"
      USERNAME: Ronak
      PASSWORD: R11
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./tmp:/storage
    restart: always
    stop_grace_period: 2m
